# Generated by Django 6.0.6 on 2026-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
